import type { Metadata } from "next";
import { Yusei_Magic } from "next/font/google";
import "./globals.css";

const yuseiMagic = Yusei_Magic({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${yuseiMagic.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
